kind: pipeline
name: test-ci
type: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.sfxcode.com
      repo: registry.sfxcode.com/vue/vite-primevue-starter
      no_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - 0.9.6
      when:
        event: push
        branch: release
